[project]
name = "math_infer_finetune"
version = "0.1.0"
description = ""
authors = [
    {name = "fe-bit"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "dotenv (>=0.9.9,<0.10.0)",
    "langgraph (>=0.4.8,<0.5.0)",
    "transformers (>=4.52.2)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)",
    "huggingface-hub (>=0.30.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "torch (>=2.7.1,<3.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
]

[tool.poetry.dependencies]
math-datasets = {develop = true}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
