compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: "2001:4ca0:4000:0:141:84:220:88"
main_process_port: 29500
num_machines: 2
num_processes: 2
use_cpu: false
